### ISSUE TITLE
About the model weights

### ISSUE THREAD

**Issue by ireneMsm2020** [jiaowoguanren0615/MobileNetV4#1]
Is there a plan to publish the model weights?

**Comment by jiaowoguanren0615** [comment]
The official team offer the TF weights, you can use weight_converter.py for converting TF weights to pytorch weights.

**Comment by Tomorrow0987** [comment]
Hello, I couldn't find the official weight for MobileNetv4. Can you provide me with a website to download the weight? thank you

**Comment by jiaowoguanren0615** [comment]
Sure! You can find torch version weights in huggingface website, the website is: [MobileNetV4 weights](https://huggingface.co/blog/rwightman/mobilenetv4)

**Comment by jiaowoguanren0615** [comment]
> Is there a plan to publish the model weights?

Now you can download the pretrained_weights in timm, the huggingface website is [MobileNetV4 pretrained_weights](https://huggingface.co/blog/rwightman/mobilenetv4)

**Comment by LLLLLLLloser** [comment]
> > 是否有计划发布模型权重？
> 
> 现在您可以在 timm 中下载 pretrained_weights，huggingface 网站是 [MobileNetV4 pretrained_weights](https://huggingface.co/blog/rwightman/mobilenetv4)

我运行import timm

model = timm.create_model("hf_hub:timm/mobilenetv1_100.ra4_e3600_r224_in1k", pretrained=True)
回显一下是什么原因呢，timm库要更新吗
C:\anaconda\envs\pytorch\python.exe C:/Users/Administrator/Desktop/track_code/HiFT-main/pretrained_models/Timm_mobilenetV4.py
C:\anaconda\envs\pytorch\lib\site-packages\huggingface_hub\file_download.py:671: FutureWarning: 'cached_download' is the legacy way to download files from the HF hub, please consider upgrading to 'hf_hub_download'
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\track_code\HiFT-main\pretrained_models\Timm_mobilenetV4.py", line 3, in <module>
    model = timm.create_model("hf_hub:timm/mobilenetv1_100.ra4_e3600_r224_in1k", pretrained=True)
  File "C:\anaconda\envs\pytorch\lib\site-packages\timm\models\factory.py", line 71, in create_model
    raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (mobilenetv1_100)

**Comment by jiaowoguanren0615** [comment]
你这里写的不是mobilenetV1么？我这个是V4的权重地址呀
"timm.create_model("hf_hub:timm/mobilenetv1_100.ra4_e3600_r224_in1k", pretrained=True)"




1105374939
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiaowoguanren0615/MobileNetV4"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月11日(星期五) 下午5:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiaowoguanren0615/MobileNetV4] About the model weights (Issue #1)





   
是否有计划发布模型权重？
  
现在您可以在 timm 中下载 pretrained_weights，huggingface 网站是 MobileNetV4 pretrained_weights
  
我运行import timm
 
model = timm.create_model("hf_hub:timm/mobilenetv1_100.ra4_e3600_r224_in1k", pretrained=True)
 回显一下是什么原因呢，timm库要更新吗
 C:\anaconda\envs\pytorch\python.exe C:/Users/Administrator/Desktop/track_code/HiFT-main/pretrained_models/Timm_mobilenetV4.py
 C:\anaconda\envs\pytorch\lib\site-packages\huggingface_hub\file_download.py:671: FutureWarning: 'cached_download' is the legacy way to download files from the HF hub, please consider upgrading to 'hf_hub_download'
 warnings.warn(
 Traceback (most recent call last):
 File "C:\Users\Administrator\Desktop\track_code\HiFT-main\pretrained_models\Timm_mobilenetV4.py", line 3, in 
 model = timm.create_model("hf_hub:timm/mobilenetv1_100.ra4_e3600_r224_in1k", pretrained=True)
 File "C:\anaconda\envs\pytorch\lib\site-packages\timm\models\factory.py", line 71, in create_model
 raise RuntimeError('Unknown model (%s)' % model_name)
 RuntimeError: Unknown model (mobilenetv1_100)

**Comment by jiaowoguanren0615** [comment]
这个是我在huggingface上timm官方库里面找的模型，如果你的名称字符串正确的话，那么就应该是timm库的版本问题


1105374939
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiaowoguanren0615/MobileNetV4"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月11日(星期五) 下午5:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiaowoguanren0615/MobileNetV4] About the model weights (Issue #1)





   
是否有计划发布模型权重？
  
现在您可以在 timm 中下载 pretrained_weights，huggingface 网站是 MobileNetV4 pretrained_weights
  
我运行import timm
 
model = timm.create_model("hf_hub:timm/mobilenetv1_100.ra4_e3600_r224_in1k", pretrained=True)
 回显一下是什么原因呢，timm库要更新吗
 C:\anaconda\envs\pytorch\python.exe C:/Users/Administrator/Desktop/track_code/HiFT-main/pretrained_models/Timm_mobilenetV4.py
 C:\anaconda\envs\pytorch\lib\site-packages\huggingface_hub\file_download.py:671: FutureWarning: 'cached_download' is the legacy way to download files from the HF hub, please consider upgrading to 'hf_hub_download'
 warnings.warn(
 Traceback (most recent call last):
 File "C:\Users\Administrator\Desktop\track_code\HiFT-main\pretrained_models\Timm_mobilenetV4.py", line 3, in 
 model = timm.create_model("hf_hub:timm/mobilenetv1_100.ra4_e3600_r224_in1k", pretrained=True)
 File "C:\anaconda\envs\pytorch\lib\site-packages\timm\models\factory.py", line 71, in create_model
 raise RuntimeError('Unknown model (%s)' % model_name)
 RuntimeError: Unknown model (mobilenetv1_100)

**Comment by LLLLLLLloser** [comment]
> 这个是我在huggingface上timm官方库里面找的模型，如果你的名称字符串正确的话，那么就应该是timm库的版本问题 1105374939 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaowoguanren0615/MobileNetV4" ***@***.***&gt;; 发送时间:&nbsp;2024年10月11日(星期五) 下午5:12 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [jiaowoguanren0615/MobileNetV4] About the model weights (Issue #1) 是否有计划发布模型权重？ 现在您可以在 timm 中下载 pretrained_weights，huggingface 网站是 MobileNetV4 pretrained_weights 我运行import timm model = timm.create_model("hf_hub:timm/mobilenetv1_100.ra4_e3600_r224_in1k", pretrained=True) 回显一下是什么原因呢，timm库要更新吗 C:\anaconda\envs\pytorch\python.exe C:/Users/Administrator/Desktop/track_code/HiFT-main/pretrained_models/Timm_mobilenetV4.py C:\anaconda\envs\pytorch\lib\site-packages\huggingface_hub\file_download.py:671: FutureWarning: 'cached_download' is the legacy way to download files from the HF hub, please consider upgrading to 'hf_hub_download' warnings.warn( Traceback (most recent call last): File "C:\Users\Administrator\Desktop\track_code\HiFT-main\pretrained_models\Timm_mobilenetV4.py", line 3, in model = timm.create_model("hf_hub:timm/mobilenetv1_100.ra4_e3600_r224_in1k", pretrained=True) File "C:\anaconda\envs\pytorch\lib\site-packages\timm\models\factory.py", line 71, in create_model raise RuntimeError('Unknown model (%s)' % model_name) RuntimeError: Unknown model (mobilenetv1_100) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
谢谢您，我的timm库更新以后就好了

**Comment by LLLLLLLloser** [comment]
> > 是否有计划发布模型权重？
> 
> 现在您可以在 timm 中下载 pretrained_weights，huggingface 网站是 [MobileNetV4 pretrained_weights](https://huggingface.co/blog/rwightman/mobilenetv4)

我下载以后的文件为model..safetensors文件，请问这是pytorch权重吗

**Comment by jiaowoguanren0615** [comment]
> > > 是否有计划发布模型权重？
> > 
> > 
> > 现在您可以在 timm 中下载 pretrained_weights，huggingface 网站是 [MobileNetV4 pretrained_weights](https://huggingface.co/blog/rwightman/mobilenetv4)
> 
> 我下载以后的文件为model..safetensors文件，请问这是pytorch权重吗
是的，其实你下载然后本地加载权重，和你直接timm库导包，然后自动帮你下载加载权重的，都是这个文件，看你想手动还是自动了

**Comment by LLLLLLLloser** [comment]
> > > > 是否有计划发布模型权重？
> > > 
> > > 
> > > 现在您可以在 timm 中下载 pretrained_weights，huggingface 网站是 [MobileNetV4 pretrained_weights](https://huggingface.co/blog/rwightman/mobilenetv4)
> > 
> > 
> > 我下载以后的文件为model..safetensors文件，请问这是pytorch权重吗
> > 是的，其实你下载然后本地加载权重，和你直接timm库导包，然后自动帮你下载加载权重的，都是这个文件，看你想手动还是自动了
非常感谢您！！！

**Comment by jiaowoguanren0615** [comment]
> > > > > 是否有计划发布模型权重？
> > > > 
> > > > 
> > > > 现在您可以在 timm 中下载 pretrained_weights，huggingface 网站是 [MobileNetV4 pretrained_weights](https://huggingface.co/blog/rwightman/mobilenetv4)
> > > 
> > > 
> > > 我下载以后的文件为model..safetensors文件，请问这是pytorch权重吗
> > > 是的，其实你下载然后本地加载权重，和你直接timm库导包，然后自动帮你下载加载权重的，都是这个文件，看你想手动还是自动了
> > > 非常感谢您！！！

客气~

**Comment by LLLLLLLloser** [comment]
> > > > > > 是否有计划发布模型权重？
> > > > > 
> > > > > 
> > > > > 现在您可以在 timm 中下载 pretrained_weights，huggingface 网站是 [MobileNetV4 pretrained_weights](https://huggingface.co/blog/rwightman/mobilenetv4)
> > > > 
> > > > 
> > > > 我下载以后的文件为模型..safetensors文件，请问这是pytorch权重吗 是的，其实你下载然后本地加载权重，和你直接timm库导包，然后自动帮你下载加载权重的，都是这个文件，看你想手动还是自动了 非常感谢您!!
> 
> 客气~

非常抱歉再次打扰您！！我在训练mobilenetv4时，加入了huggingface的权重。但是报错回显为_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.我该怎么解决

**Comment by jiaowoguanren0615** [comment]
> > > > > > > 是否有计划发布模型权重？
> > > > > > 
> > > > > > 
> > > > > > 现在您可以在 timm 中下载 pretrained_weights，huggingface 网站是 [MobileNetV4 pretrained_weights](https://huggingface.co/blog/rwightman/mobilenetv4)
> > > > > 
> > > > > 
> > > > > 我下载以后的文件为模型..safetensors文件，请问这是pytorch权重吗 是的，其实你下载然后本地加载权重，和你直接timm库导包，然后自动帮你下载加载权重的，都是这个文件，看你想手动还是自动了 非常感谢您!!
> > 
> > 
> > 客气~
> 
> 非常抱歉再次打扰您！！我在训练mobilenetv4时，加入了huggingface的权重。但是报错回显为_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.我该怎么解决

你用一下timm官方给出的实例代码加载试试呢？https://huggingface.co/timm/mobilenetv4_conv_small_050.e3000_r224_in1k

**Comment by jiaowoguanren0615** [comment]
> > > > > > > 是否有计划发布模型权重？
> > > > > > 
> > > > > > 
> > > > > > 现在您可以在 timm 中下载 pretrained_weights，huggingface 网站是 [MobileNetV4 pretrained_weights](https://huggingface.co/blog/rwightman/mobilenetv4)
> > > > > 
> > > > > 
> > > > > 我下载以后的文件为模型..safetensors文件，请问这是pytorch权重吗 是的，其实你下载然后本地加载权重，和你直接timm库导包，然后自动帮你下载加载权重的，都是这个文件，看你想手动还是自动了 非常感谢您!!
> > 
> > 
> > 客气~
> 
> 非常抱歉再次打扰您！！我在训练mobilenetv4时，加入了huggingface的权重。但是报错回显为_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.我该怎么解决

这里说明可能是pytorch版本的问题，https://geek-docs.com/pytorch/pytorch-questions/80_pytorch_unpicklingerror_a_load_persistent_id_instruction_was_encountered_but_no_persistent_load_function_was_specified.html，这种东西有的时候就比较玄学，你的conda环境里面transformers pytorch timm 版本可能会导致这类问题，更新了还不行的话就直接用timm直接加载模型，然后改一下分类头的output_features数量吧

**Comment by jiaowoguanren0615** [comment]
> > > > > > > 是否有计划发布模型权重？
> > > > > > 
> > > > > > 
> > > > > > 现在您可以在 timm 中下载 pretrained_weights，huggingface 网站是 [MobileNetV4 pretrained_weights](https://huggingface.co/blog/rwightman/mobilenetv4)
> > > > > 
> > > > > 
> > > > > 我下载以后的文件为模型..safetensors文件，请问这是pytorch权重吗 是的，其实你下载然后本地加载权重，和你直接timm库导包，然后自动帮你下载加载权重的，都是这个文件，看你想手动还是自动了 非常感谢您!!
> > 
> > 
> > 客气~
> 
> 非常抱歉再次打扰您！！我在训练mobilenetv4时，加入了huggingface的权重。但是报错回显为_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.我该怎么解决

这里说明可能是pytorch版本的问题，[(https://geek-docs.com/pytorch/pytorch-questions/80_pytorch_unpicklingerror_a_load_persistent_id_instruction_was_encountered_but_no_persistent_load_function_was_specified.html)]，这种东西有的时候就比较玄学，你的conda环境里面transformers pytorch timm 版本可能会导致这类问题，更新了还不行的话就直接用timm直接加载模型，然后改一下分类头的output_features数量吧

**Comment by jiaowoguanren0615** [comment]
> > > > > > > 是否有计划发布模型权重？
> > > > > > 
> > > > > > 
> > > > > > 现在您可以在 timm 中下载 pretrained_weights，huggingface 网站是 [MobileNetV4 pretrained_weights](https://huggingface.co/blog/rwightman/mobilenetv4)
> > > > > 
> > > > > 
> > > > > 我下载以后的文件为模型..safetensors文件，请问这是pytorch权重吗 是的，其实你下载然后本地加载权重，和你直接timm库导包，然后自动帮你下载加载权重的，都是这个文件，看你想手动还是自动了 非常感谢您!!
> > 
> > 
> > 客气~
> 
> 非常抱歉再次打扰您！！我在训练mobilenetv4时，加入了huggingface的权重。但是报错回显为_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.我该怎么解决

这里说明可能是pytorch版本的问题，[https://geek-docs.com/pytorch/pytorch-questions/80_pytorch_unpicklingerror_a_load_persistent_id_instruction_was_encountered_but_no_persistent_load_function_was_specified.html]，这种东西有的时候就比较玄学，你的conda环境里面transformers pytorch timm 版本可能会导致这类问题，更新了还不行的话就直接用timm直接加载模型，然后改一下分类头的output_features数量吧

**Comment by LLLLLLLloser** [comment]
> > > > > > > > 是否有计划发布模型权重？
> > > > > > > 
> > > > > > > 
> > > > > > > 现在您可以在 timm 中下载 pretrained_weights，huggingface 网站是 [MobileNetV4 pretrained_weights](https://huggingface.co/blog/rwightman/mobilenetv4)
> > > > > > 
> > > > > > 
> > > > > > 我下载以后的文件为模型..safetensors文件，请问这是pytorch权重吗 是的，其实你下载然后本地加载权重，和你直接timm库导包，然后自动帮你下载加载权重的，都是这个文件，看你想手动还是自动了 非常感谢您!!
> > > 
> > > 
> > > 客气~
> > 
> > 
> > 非常抱歉再次打扰您！！我在训练mobilenetv4时，加入了huggingface的权重。但是报错回显为_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.我该怎么解决
> 
> 这里说明可能是pytorch版本的问题，[https://geek-docs.com/pytorch/pytorch-questions/80_pytorch_unpicklingerror_a_load_persistent_id_instruction_was_encountered_but_no_persistent_load_function_was_specified.html]，这种东西有的时候就比较玄学，你的conda环境里面transformers pytorch timm 版本可能会导致这类问题，更新了还不行的话就直接用timm直接加载模型，然后改一下分类头的output_features数量吧

好嘞我试试，你是我爹

**Comment by jiaowoguanren0615** [comment]
> > > > > > > > > 是否有计划发布模型权重？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 现在您可以在 timm 中下载 pretrained_weights，huggingface 网站是 [MobileNetV4 pretrained_weights](https://huggingface.co/blog/rwightman/mobilenetv4)
> > > > > > > 
> > > > > > > 
> > > > > > > 我下载以后的文件为模型..safetensors文件，请问这是pytorch权重吗 是的，其实你下载然后本地加载权重，和你直接timm库导包，然后自动帮你下载加载权重的，都是这个文件，看你想手动还是自动了 非常感谢您!!
> > > > 
> > > > 
> > > > 客气~
> > > 
> > > 
> > > 非常抱歉再次打扰您！！我在训练mobilenetv4时，加入了huggingface的权重。但是报错回显为_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.我该怎么解决
> > 
> > 
> > 这里说明可能是pytorch版本的问题，[https://geek-docs.com/pytorch/pytorch-questions/80_pytorch_unpicklingerror_a_load_persistent_id_instruction_was_encountered_but_no_persistent_load_function_was_specified.html]，这种东西有的时候就比较玄学，你的conda环境里面transformers pytorch timm 版本可能会导致这类问题，更新了还不行的话就直接用timm直接加载模型，然后改一下分类头的output_features数量吧
> 
> 好嘞我试试，你是我爹

艹。绷不住了

**Comment by LLLLLLLloser** [comment]
'features.blocks.2.4.pw_exp.bn.running_mean', 'features.blocks.3.0.pw_exp.bn.running_var', 'features.blocks.2.1.pw_proj.conv.weight', 'features.blocks.2.1.dw_mid.conv.weight', 'features.blocks.2.5.pw_exp.conv.weight', 'features.blocks.3.2.pw_exp.bn.running_mean', 'features.blocks.3.2.dw_mid.bn.running_mean', 'features.blocks.2.2.pw_exp.bn.num_batches_tracked', 'features.blocks.2.4.pw_proj.conv.weight', 'features.blocks.3.5.dw_mid.bn.weight', 'features.blocks.4.0.bn1.running_mean', 'features.blocks.2.0.dw_start.bn.weight', 'features.blocks.3.0.pw_proj.bn.num_batches_tracked', 'features.blocks.3.3.pw_exp.bn.weight', 'features.blocks.2.2.pw_proj.bn.bias', 'features.blocks.3.3.pw_proj.bn.weight', 'features.blocks.1.0.bn1.weight', 'features.blocks.1.0.bn1.num_batches_tracked'}
[2024-10-23 17:39:15,832-rk0-model_load.py# 31] unused checkpoint keys:278
[2024-10-23 17:39:15,832-rk0-model_load.py# 33] used keys:0
Traceback (most recent call last):
  File "/data1/ZMY/HiFT-main/pysot/utils/model_load.py", line 59, in load_pretrain
    check_keys(model, pretrained_dict)
  File "/data1/ZMY/HiFT-main/pysot/utils/model_load.py", line 34, in check_keys
    assert len(used_pretrained_keys) > 0, \
AssertionError: load NONE from pretrained checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data1/ZMY/HiFT-main/tools/train.py", line 275, in <module>
    main()
  File "/data1/ZMY/HiFT-main/tools/train.py", line 236, in main
    load_pretrain(model.backbone, backbone_path)
  File "/data1/ZMY/HiFT-main/pysot/utils/model_load.py", line 68, in load_pretrain
    check_keys(model, pretrained_dict)
  File "/data1/ZMY/HiFT-main/pysot/utils/model_load.py", line 34, in check_keys
    assert len(used_pretrained_keys) > 0, \
AssertionError: load NONE from pretrained checkpoint                                                                                                                                    我在使用small的backbone替换我自己代码的backbone，加入了.bin的权重。训练时模型和权重应该是不匹配，
[2024-10-23 17:39:15,832-rk0-model_load.py# 31] unused checkpoint keys:278
[2024-10-23 17:39:15,832-rk0-model_load.py# 33] used keys:0
这种权重损坏还是其他问题

**Comment by jiaowoguanren0615** [comment]
> 'features.blocks.2.4.pw_exp.bn.running_mean', 'features.blocks.3.0.pw_exp.bn.running_var', 'features.blocks.2.1.pw_proj.conv.weight', 'features.blocks.2.1.dw_mid.conv.weight', 'features.blocks.2.5.pw_exp.conv.weight', 'features.blocks.3.2.pw_exp.bn.running_mean', 'features.blocks.3.2.dw_mid.bn.running_mean', 'features.blocks.2.2.pw_exp.bn.num_batches_tracked', 'features.blocks.2.4.pw_proj.conv.weight', 'features.blocks.3.5.dw_mid.bn.weight', 'features.blocks.4.0.bn1.running_mean', 'features.blocks.2.0.dw_start.bn.weight', 'features.blocks.3.0.pw_proj.bn.num_batches_tracked', 'features.blocks.3.3.pw_exp.bn.weight', 'features.blocks.2.2.pw_proj.bn.bias', 'features.blocks.3.3.pw_proj.bn.weight', 'features.blocks.1.0.bn1.weight', 'features.blocks.1.0.bn1.num_batches_tracked'} [2024-10-23 17:39:15,832-rk0-model_load.py# 31] unused checkpoint keys:278 [2024-10-23 17:39:15,832-rk0-model_load.py# 33] used keys:0 Traceback (most recent call last): File "/data1/ZMY/HiFT-main/pysot/utils/model_load.py", line 59, in load_pretrain check_keys(model, pretrained_dict) File "/data1/ZMY/HiFT-main/pysot/utils/model_load.py", line 34, in check_keys assert len(used_pretrained_keys) > 0, AssertionError: load NONE from pretrained checkpoint
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/data1/ZMY/HiFT-main/tools/train.py", line 275, in main() File "/data1/ZMY/HiFT-main/tools/train.py", line 236, in main load_pretrain(model.backbone, backbone_path) File "/data1/ZMY/HiFT-main/pysot/utils/model_load.py", line 68, in load_pretrain check_keys(model, pretrained_dict) File "/data1/ZMY/HiFT-main/pysot/utils/model_load.py", line 34, in check_keys assert len(used_pretrained_keys) > 0, AssertionError: load NONE from pretrained checkpoint 我在使用small的backbone替换我自己代码的backbone，加入了.bin的权重。训练时模型和权重应该是不匹配， [2024-10-23 17:39:15,832-rk0-model_load.py# 31] unused checkpoint keys:278 [2024-10-23 17:39:15,832-rk0-model_load.py# 33] used keys:0 这种权重损坏还是其他问题

assert报错是因为len(used_pretrained_keys) = 0触发了assert，那就说明是你什么都没加载，大概率是权重损坏的问题

**Comment by jiaowoguanren0615** [comment]
> 'features.blocks.2.4.pw_exp.bn.running_mean', 'features.blocks.3.0.pw_exp.bn.running_var', 'features.blocks.2.1.pw_proj.conv.weight', 'features.blocks.2.1.dw_mid.conv.weight', 'features.blocks.2.5.pw_exp.conv.weight', 'features.blocks.3.2.pw_exp.bn.running_mean', 'features.blocks.3.2.dw_mid.bn.running_mean', 'features.blocks.2.2.pw_exp.bn.num_batches_tracked', 'features.blocks.2.4.pw_proj.conv.weight', 'features.blocks.3.5.dw_mid.bn.weight', 'features.blocks.4.0.bn1.running_mean', 'features.blocks.2.0.dw_start.bn.weight', 'features.blocks.3.0.pw_proj.bn.num_batches_tracked', 'features.blocks.3.3.pw_exp.bn.weight', 'features.blocks.2.2.pw_proj.bn.bias', 'features.blocks.3.3.pw_proj.bn.weight', 'features.blocks.1.0.bn1.weight', 'features.blocks.1.0.bn1.num_batches_tracked'} [2024-10-23 17:39:15,832-rk0-model_load.py# 31] unused checkpoint keys:278 [2024-10-23 17:39:15,832-rk0-model_load.py# 33] used keys:0 Traceback (most recent call last): File "/data1/ZMY/HiFT-main/pysot/utils/model_load.py", line 59, in load_pretrain check_keys(model, pretrained_dict) File "/data1/ZMY/HiFT-main/pysot/utils/model_load.py", line 34, in check_keys assert len(used_pretrained_keys) > 0, AssertionError: load NONE from pretrained checkpoint
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/data1/ZMY/HiFT-main/tools/train.py", line 275, in main() File "/data1/ZMY/HiFT-main/tools/train.py", line 236, in main load_pretrain(model.backbone, backbone_path) File "/data1/ZMY/HiFT-main/pysot/utils/model_load.py", line 68, in load_pretrain check_keys(model, pretrained_dict) File "/data1/ZMY/HiFT-main/pysot/utils/model_load.py", line 34, in check_keys assert len(used_pretrained_keys) > 0, AssertionError: load NONE from pretrained checkpoint 我在使用small的backbone替换我自己代码的backbone，加入了.bin的权重。训练时模型和权重应该是不匹配， [2024-10-23 17:39:15,832-rk0-model_load.py# 31] unused checkpoint keys:278 [2024-10-23 17:39:15,832-rk0-model_load.py# 33] used keys:0 这种权重损坏还是其他问题

我找到你这个代码的github源码了，used_pretrained_keys = model_keys & ckpt_keys，它是用交集运算符的，那就说明small的backbone里面的命名和权重文件里面的不一样，所以在比较key字符串的时候，没有完全符合的key，导致这个assert报错了，如果你想看small里面的每一层的名字，直接print(backbone)就可以了

**Comment by jiaowoguanren0615** [comment]
> 'features.blocks.2.4.pw_exp.bn.running_mean', 'features.blocks.3.0.pw_exp.bn.running_var', 'features.blocks.2.1.pw_proj.conv.weight', 'features.blocks.2.1.dw_mid.conv.weight', 'features.blocks.2.5.pw_exp.conv.weight', 'features.blocks.3.2.pw_exp.bn.running_mean', 'features.blocks.3.2.dw_mid.bn.running_mean', 'features.blocks.2.2.pw_exp.bn.num_batches_tracked', 'features.blocks.2.4.pw_proj.conv.weight', 'features.blocks.3.5.dw_mid.bn.weight', 'features.blocks.4.0.bn1.running_mean', 'features.blocks.2.0.dw_start.bn.weight', 'features.blocks.3.0.pw_proj.bn.num_batches_tracked', 'features.blocks.3.3.pw_exp.bn.weight', 'features.blocks.2.2.pw_proj.bn.bias', 'features.blocks.3.3.pw_proj.bn.weight', 'features.blocks.1.0.bn1.weight', 'features.blocks.1.0.bn1.num_batches_tracked'} [2024-10-23 17:39:15,832-rk0-model_load.py# 31] unused checkpoint keys:278 [2024-10-23 17:39:15,832-rk0-model_load.py# 33] used keys:0 Traceback (most recent call last): File "/data1/ZMY/HiFT-main/pysot/utils/model_load.py", line 59, in load_pretrain check_keys(model, pretrained_dict) File "/data1/ZMY/HiFT-main/pysot/utils/model_load.py", line 34, in check_keys assert len(used_pretrained_keys) > 0, AssertionError: load NONE from pretrained checkpoint
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/data1/ZMY/HiFT-main/tools/train.py", line 275, in main() File "/data1/ZMY/HiFT-main/tools/train.py", line 236, in main load_pretrain(model.backbone, backbone_path) File "/data1/ZMY/HiFT-main/pysot/utils/model_load.py", line 68, in load_pretrain check_keys(model, pretrained_dict) File "/data1/ZMY/HiFT-main/pysot/utils/model_load.py", line 34, in check_keys assert len(used_pretrained_keys) > 0, AssertionError: load NONE from pretrained checkpoint 我在使用small的backbone替换我自己代码的backbone，加入了.bin的权重。训练时模型和权重应该是不匹配， [2024-10-23 17:39:15,832-rk0-model_load.py# 31] unused checkpoint keys:278 [2024-10-23 17:39:15,832-rk0-model_load.py# 33] used keys:0 这种权重损坏还是其他问题

如果你可以换一个backbone的话，可以去我另一个仓库看看 [代码仓库](https://github.com/jiaowoguanren0615/Segmentation_Factory/blob/main/models/backbones/mit.py) 加载权重示例代码在最下面，mit模型权重文件[下载地址](https://connecthkuhk-my.sharepoint.com/personal/xieenze_connect_hku_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fxieenze%5Fconnect%5Fhku%5Fhk%2FDocuments%2Fsegformer%2Fpretrained%5Fmodels&ga=1) 我用mit-b0试了我的代码，加载没有问题，权重文件包含了分类头的，所以load_state_dict的时候记得加上strict=False

**Comment by liwer0715** [comment]
加载了hugging face提供的权重后，模型推理是正常的吗？我测试全是错误的

**Comment by jiaowoguanren0615** [comment]
> 加载了hugging face提供的权重后，模型推理是正常的吗？我测试全是错误的

如果是因为用这个代码无法加载权重，可以去timm库把timm官方实现的pytorch代码复制一份，就可以加载权重了，或者直接timm导包也行，我这个仓库的代码不是timm的官方实现方式，如果是能加载权重，你最好看一下你加载权重load_state_dict的时候是不是加上了strict=False，加了这个即便layer名称不符合，也不会报错，个人建议直接导包，省时省力，除了模型搭建和timm官方的不一样之外，其余预测或者部署部分的代码应该是可以直接运行

**Comment by jiaowoguanren0615** [comment]
> 加载了hugging face提供的权重后，模型推理是正常的吗？我测试全是错误的

[源码地址](https://github.com/huggingface/pytorch-image-models/blob/eb94efb21817eb68629cfab63083bfa34ddddd70/timm/models/mobilenetv3.py)，timm库把mobilenetv3和mobilenetv4放在一起了

**Comment by liwer0715** [comment]
您提供的代码我匹配了一下key和values，虽然key与timm的权重文件加载出来的名称不一样，但是values的shape是完全对齐的，但是结果就是不对，是因为forward计算流程有差异？

**Comment by jiaowoguanren0615** [comment]
> 您提供的代码我匹配了一下key和values，虽然key与timm的权重文件加载出来的名称不一样，但是values的shape是完全对齐的，但是结果就是不对，是因为forward计算流程有差异？

我匹配了一下官方给的safetensors权重文件，发现和我的模型有很多mismatch，你说的对齐应该是官方给的bin文件对吧，我也试了一下，bin文件没问题，但是运行的准确率很低，safetensors权重文件里面有很多mismatch，我稍后看一下官方的模型搭建实现方式，改一下

**Comment by Data-Adventure** [comment]
这个问题是否解决了？

**Comment by jiaowoguanren0615** [comment]
> 这个问题是否解决了？

您好，现在已经解决了，直接去下载权重然后load就行

**Comment by Data-Adventure** [comment]
> > 这个问题是否解决了？
> 
> 您好，现在已经解决了，直接去下载权重然后load就行

谢谢作者的工作
